name: quickdrop
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.5
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dart_code_metrics: null
flutter:
  uses-material-design: true