name: quickdrop
description: "Tesis project"

publish_to: "none"
version: "1.8.0"
repository: https://github.com/4CROS2/quickdrop.git


environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.5.2  
  firebase_core: ^3.13.0
  flutter_bloc: ^9.1.0
  cloud_firestore: ^5.6.6
  equatable: ^2.0.7
  hydrated_bloc: ^10.0.0
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.3.0
  rxdart: ^0.27.7
  go_router: ^14.8.1
  http: ^1.3.0
  firebase_storage: ^12.4.5
  shimmer: ^3.0.0
  extensions: 
    git: 
      url: https://github.com/4CROS2/string_extensions.git 
      ref: main
  apptoastification:
    git:
      url: https://github.com/4CROS2/apptoastification.git
      ref: main
  uuid: ^4.5.1
  pretty_qr_code: ^3.3.0
  custom_rating_bar: ^3.0.0
  hugeicons: ^0.0.10
  location: ^8.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  flutter_map: ^8.1.1
  image: ^4.5.4
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: null
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/svg/
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf
    - family: Redhat
      fonts:
        - asset: assets/fonts/redhat_bold.ttf
          weight: 700
        - asset: assets/fonts/redhat_semi.ttf
          weight: 500
        - asset: assets/fonts/redhat_regular.ttf
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/albert_sans/AlbertSans-Black.ttf
          weight: 900
        - asset: assets/fonts/albert_sans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/albert_sans/AlbertSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/albert_sans/AlbertSans-Light.ttf
          weight: 300
        - asset: assets/fonts/albert_sans/AlbertSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/albert_sans/AlbertSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/albert_sans/AlbertSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/albert_sans/AlbertSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/albert_sans/AlbertSans-Thin.ttf
          weight: 100

