name: quickdrop
description: "Tesis project"

publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.5.1
  firebase_core: ^3.11.0
  flutter_bloc: ^9.0.0
  cloud_firestore: ^5.6.5
  equatable: ^2.0.7
  hydrated_bloc: ^10.0.0
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.2
  rxdart: ^0.27.7
  go_router: ^14.8.0
  http: ^1.3.0
  firebase_storage: ^12.4.4
  shimmer: ^3.0.0
  extensions: 
    git: 
      url: https://github.com/4CROS2/string_extensions.git 
      ref: main
  toastification: ^3.0.2
  uuid: ^4.5.1
  pretty_qr_code: ^3.3.0
  custom_rating_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: null
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/svg/
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf
    - family: Redhat
      fonts:
        - asset: assets/fonts/redhat_bold.ttf
          weight: 700
        - asset: assets/fonts/redhat_semi.ttf
          weight: 500
        - asset: assets/fonts/redhat_regular.ttf

