name: quickdrop
description: "Tesis project"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.5
  get_it: ^8.0.2
  flutter_svg: ^2.0.12
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.2
  rxdart: ^0.27.7
  firebase_storage: ^12.3.4
  http: ^1.2.2
  go_router: ^14.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: null
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/svg/
  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf
    - family: Redhat
      fonts:
        - asset: assets/fonts/redhat_bold.ttf
          weight: 700
        - asset: assets/fonts/redhat_semi.ttf
          weight: 500
        - asset: assets/fonts/redhat_regular.ttf

